name: crash_cart_mediq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 📁 Pour permettre la sélection et la lecture de fichiers médicaux
  file_picker: ^8.0.0     # sélection du fichier (.csv / .xlsx)
  csv: ^6.0.0              # lecture et parsing des fichiers CSV
  excel: ^4.0.2            # lecture des fichiers Excel (.xlsx)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

file_picker: ^8.0.0
